# Site settings
title: dario Blog
header-img: img/home-bg.jpg
email: contact@dario.com
copyright_name: Your/Project/Corporate Name
description: "dario.com blog or resource page. It will be used as your sites meta description as well!"
baseurl: "/blog"
url: "https://dario.com"
twitter_username: darioS3C
github_username:  
facebook_username:  
email_username:  email_username@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-98131817-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
